name: movieticketbooking
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  loop_page_view: ^1.2.5
  carousel_slider: ^5.0.0
  cached_network_image: ^3.3.1
  video_player: ^2.9.3
  url_launcher: ^6.3.1
  intl: ^0.20.0
  qr_flutter: ^4.1.0
  provider: ^6.1.2
  fl_chart: ^0.67.0
  image_picker: ^1.1.2
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10
  firebase_messaging: ^14.7.19
  firebase_analytics: ^10.8.10
  firebase_app_check: ^0.2.1+18
  mailer: ^6.1.0
  http: ^1.2.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/login.jpg
    - assets/fonts/Roboto.ttf
    - assets/icons/user.png
    - assets/images/logo.png
    - assets/icons/buyticket.png
    - assets/icons/film.png
    - assets/icons/sale.png
    - assets/icons/theater.png
    - assets/icons/myticket.png
    - assets/images/bapnuoc.png
