// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr-mTQ6f7yWciI-bdWFJ4BdSbFfOc7R6A',
    appId: '1:1057126870012:web:991dec3e4b70abd7c6a079',
    messagingSenderId: '1057126870012',
    projectId: 'moviebookingticketapp-74862',
    authDomain: 'moviebookingticketapp-74862.firebaseapp.com',
    storageBucket: 'moviebookingticketapp-74862.firebasestorage.app',
    measurementId: 'G-3FC606DB2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSgQz20ufSjUcw1tuX7pRv-iLcJk88eW8',
    appId: '1:1057126870012:android:a74ff70fb00ed660c6a079',
    messagingSenderId: '1057126870012',
    projectId: 'moviebookingticketapp-74862',
    storageBucket: 'moviebookingticketapp-74862.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc8F_R6DazZ1ErDo2coL0ItWnEWazxuQI',
    appId: '1:1057126870012:ios:ffba466aaee4c569c6a079',
    messagingSenderId: '1057126870012',
    projectId: 'moviebookingticketapp-74862',
    storageBucket: 'moviebookingticketapp-74862.firebasestorage.app',
    iosBundleId: 'com.example.movieticketbooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc8F_R6DazZ1ErDo2coL0ItWnEWazxuQI',
    appId: '1:1057126870012:ios:ffba466aaee4c569c6a079',
    messagingSenderId: '1057126870012',
    projectId: 'moviebookingticketapp-74862',
    storageBucket: 'moviebookingticketapp-74862.firebasestorage.app',
    iosBundleId: 'com.example.movieticketbooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr-mTQ6f7yWciI-bdWFJ4BdSbFfOc7R6A',
    appId: '1:1057126870012:web:aea8989ac8097944c6a079',
    messagingSenderId: '1057126870012',
    projectId: 'moviebookingticketapp-74862',
    authDomain: 'moviebookingticketapp-74862.firebaseapp.com',
    storageBucket: 'moviebookingticketapp-74862.firebasestorage.app',
    measurementId: 'G-VG5DDQ5Q2L',
  );
}
